export const BootCampTapOptions = [
  //Tap 옵션
  '전체보기',
  '역대 수상작',
  '10기',
  '9기',
  '8기',
  '7기',
  '6기',
  '5기',
  '4기',
  '3기',
  '2기',
  '1기',
]

export const allBootcampProject = [
  //임시 데이터
  {
    id: 1,
    year: 1,
    image_url: '/images/bootcamp/bootcampImage.svg',
    rank: 1,
  },
  {
    id: 2,
    year: 2,
    image_url: '/images/bootcamp/bootcampImage.svg',
    rank: 2,
  },
  {
    id: 3,
    year: 2,
    image_url: '/images/bootcamp/bootcampImage.svg',
    rank: 3,
  },
  {
    id: 4,
    year: 4,
    image_url: '/images/bootcamp/bootcampImage.svg',
    rank: 3,
  },
  {
    id: 5,
    year: 3,
    image_url: '/images/bootcamp/bootcampImage.svg',
    rank: 0,
  },
  {
    id: 6,
    year: 5,
    image_url: '/images/bootcamp/bootcampImage.svg',
    rank: 0,
  },
  {
    id: 7,
    year: 6,
    image_url: '/images/bootcamp/bootcampImage.svg',
    rank: 0,
  },
  {
    id: 8,
    year: 8,
    image_url: '/images/bootcamp/bootcampImage.svg',
    rank: 0,
  },
  {
    id: 9,
    year: 7,
    image_url: '/images/bootcamp/bootcampImage.svg',
    rank: 0,
  },
  {
    id: 10,
    year: 10,
    image_url: '/images/bootcamp/bootcampImage.svg',
    rank: 0,
  },
  {
    id: 11,
    year: 8,
    image_url: '/images/bootcamp/bootcampImage.svg',
    rank: 0,
  },
  {
    id: 12,
    year: 8,
    image_url: '/images/bootcamp/bootcampImage.svg',
    rank: 0,
  },
]

export const bootcampProjectDetail = {
  id: 1,
  name: 'Next-Page',
  team: 'A',
  year: 10,
  project_explain: '상상을 현실로, 손끝에서 펼쳐지는 우리만의 세계',
  github_url: 'https://github.com/bootcamp/project',
  medium_url: 'https://medium.com/@bootcamp',
  web_url: 'https://bootcamp.com',
  image_url: '/images/bootcamp/bootcampImage.svg',
  isOpen: true,
  rank: 1,
  members: [
    { user_id: 1, teamRole: 'BACKEND', name: '주영준' },
    { user_id: 2, teamRole: 'BACKEND', name: '권유리' },
    { user_id: 3, teamRole: 'BACKEND', name: '김진희' },
    { user_id: 4, teamRole: 'BACKEND', name: '윤정은' },
    { user_id: 5, teamRole: 'BACKEND', name: '최지혜' },
    { user_id: 6, teamRole: 'FRONTEND', name: '주영준' },
    { user_id: 7, teamRole: 'FRONTEND', name: '권유리' },
    { user_id: 8, teamRole: 'FRONTEND', name: '김진희' },
    { user_id: 9, teamRole: 'FRONTEND', name: '윤정은' },
    { user_id: 10, teamRole: 'FRONTEND', name: '최지혜' },
    { user_id: 11, teamRole: 'DEV', name: '주영준' },
    { user_id: 12, teamRole: 'DEV', name: '권유리' },
    { user_id: 13, teamRole: 'DEV', name: '김진희' },
    { user_id: 14, teamRole: 'DEV', name: '윤정은' },
    { user_id: 15, teamRole: 'DEV', name: '최지혜' },
  ],
}
